name: Hermuset
favicon: null
layout_spectrum: 0.16415
typography_spectrum: 0.79396
title: Blogi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cacaca'
    - '#838383'
    - '#4f4f4f'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
