name: Hermuset
favicon: null
layout_spectrum: 0.49588
typography_spectrum: 0.47064
title: Blogi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a252d'
    - '#ccbbaf'
    - '#b0652e'
    - '#9f8b91'
    - '#ffaa00'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
