name: Hermuset
favicon: null
layout_spectrum: 0.2546
typography_spectrum: 0.58124
title: Blogi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#804700'
    - '#75885c'
    - '#ffb87e'
    - '#fff5f6'
  brandStrength: 0
  lightness: 0.9375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
