name: Hermuset
favicon: null
layout_spectrum: 0.16834
typography_spectrum: 0.99329
title: Blogi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cacaca'
    - '#838383'
    - '#4f4f4f'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
